stages:
  - build
  - test

build:
  stage: build
  image: docker:24.0.5
  script:
    - docker build -t kgcore .

test:
  stage: test
  image: docker:24.0.5
  script:
    - docker run --rm kgcore .venv/bin/python -m pytest
